definitions:
  env_vars: &env_vars
    FIREBASE_PROJECT_ID: your-firebase-project-id
    BASE_ASSETS_URL: your-base-assets-url # Base URL for assets, excluding the specific filename

  scripts:
    - &get_assets
      name: Get assets and configuration files from Firebase Storage
      script: |
        # Ensure Firebase CLI is installed
        curl -sL https://firebase.tools | bash
        
        # Authenticate with Firebase
        firebase login:ci --token $FIREBASE_TOKEN
        
        # Dynamic asset file name based on CLIENT_ID
        ASSET_FILE_NAME="assets_${CLIENT_ID}.zip"
        
        # Construct the full URL for the assets file
        ASSETS_URL="${BASE_ASSETS_URL}/${ASSET_FILE_NAME}"

        # Download client-specific assets
        echo "Downloading assets from ${ASSETS_URL}"
        curl -o client_assets.zip $ASSETS_URL || echo "Failed to download ${ASSET_FILE_NAME}"
        unzip client_assets.zip -d ./assets

    - name: Replace assets, .env, and Google services files
      script: |
        # Replace images
        cp ./assets/images/app_launcher_icon.png ./android/app/src/main/res/mipmap/
        cp ./assets/images/app_launcher_icon.png ./ios/Runner/Assets.xcassets/AppIcon.appiconset/
        cp ./assets/images/error_image.png ./assets/images/
        
        # Replace Google services files
        cp ./assets/android/google-services.json ./android/app/
        cp ./assets/ios/GoogleService-Info.plist ./ios/Runner/

        # Replace .env file
        cp ./assets/client/client.env ./assets/

workflows:
  ios-client-release:
    name: iOS client release
    instance_type: mac_mini_m1
    labels:
      - ${CLIENT_ID}
    environment:
      vars:
        <<: *env_vars
        XCODE_SCHEME: "Runner"
        FIREBASE_TOKEN: your-firebase-ci-token
    scripts:
      - *get_assets
      - name: Replace assets, .env, and Google services files

      - name: Change iOS app name
        script: /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" -c "Set :CFBundleDisplayName $APP_NAME" ios/${XCODE_SCHEME}/Info.plist

      - name: Install dependencies
        script: flutter packages pub get
      
      - name: Flutter build ipa and automatic versioning
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
          flutter build ipa --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER\
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - test-results/flutter.json
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - name@mail.com
