workflows:
  crete-themed-app-workflow:
    name: Create Themed app
    instance_type: mac_mini_m1
    environment:
      flutter: stable    
      ios_signing:
        certificates:
          - TestClient1
          - TestClient1Development
        provisioning_profiles:
          - client1
          - client1Distribution

    integrations:
      app_store_connect: Test app - Codemagic

    triggering:
      events:
        - tag    

    scripts:
      - name: Apply client configuration
        script: |
          # Assuming CM_TAG is set to the tag that triggered the build
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          echo "A Build is going to be performed for: $CLIENT_ID"
          echo "Copy assets for client"
          cp -r "clients/$CLIENT_ID/backend" "lib/"
          cp "clients/$CLIENT_ID/flutter_flow_theme.dart" "lib/flutter_flow/flutter_flow_theme.dart"
          cp "clients/$CLIENT_ID/app_launcher_icon.png" "assets/images/app_launcher_icon.png"
          cp "clients/$CLIENT_ID/app_splash_image.png" "assets/images/app_splash_image.png"
          echo "Add dependencies for preparing assets"
          flutter pub add flutter_launcher_icons
          flutter pub add flutter_native_splash
          flutter pub get
          echo "Applying configs"
          flutter pub run flutter_launcher_icons -f "clients/clients_flutter_launcher_icons.yaml"
          flutter pub run flutter_native_splash:create --path="clients/clients_flutter_native_splash.yaml"      
          echo "Successfully applied client configuration"

          
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      
      # TODO Change package name for Android as well
      # -name: Change Android Package name
      # script: |
      # echo "Change name to com.mycompany.$CLIENT_ID"

      #- name: Build AAB with Flutter
      #  script: | 
      #    flutter build appbundle --release

      # - name: Build APK for Debug
      #   script: | 
      #     flutter build apk --debug

      - name: Change iOS Bundle Identifier
        script: |
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          NEW_BUNDLE_IDENTIFIER="com.mycompany.$CLIENT_ID"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $NEW_BUNDLE_IDENTIFIER" "$FCI_BUILD_DIR/ios/Runner/Info.plist"
          echo "Bundle Identifier changed to $NEW_BUNDLE_IDENTIFIER"
      
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles


      - name: Prepare Xcode for Build
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app using xcodebuild
        script: |
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          NEW_BUNDLE_IDENTIFIER="com.mycompany.$CLIENT_ID"
          echo "Building for $NEW_BUNDLE_IDENTIFIER with $CLIENT_ID"
          xcodebuild -workspace ios/Runner.xcworkspace \
                 -scheme Runner \
                 -sdk iphoneos \
                 -configuration Release \
                 -derivedDataPath build/ios \
                 PROVISIONING_PROFILE_SPECIFIER="Client1TestDevelopment" \
                 DEVELOPMENT_TEAM=G344VHW6HF \
                 CODE_SIGN_STYLE=Manual \
                 PRODUCT_BUNDLE_IDENTIFIER="$NEW_BUNDLE_IDENTIFIER" \
                 clean build

      - name: Archive iOS app
        script: |
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          NEW_BUNDLE_IDENTIFIER="com.mycompany.$CLIENT_ID"
          echo "Archiving for $NEW_BUNDLE_IDENTIFIER with $CLIENT_ID"
          xcodebuild archive -workspace ios/Runner.xcworkspace \
                -scheme Runner \
                -configuration Release \
                -archivePath $FCI_BUILD_DIR/build/Runner.xcarchive \
                -destination 'generic/platform=iOS' \
                PROVISIONING_PROFILE_SPECIFIER="Client1TestDevelopment" \
                DEVELOPMENT_TEAM="G344VHW6HF" \
                CODE_SIGN_STYLE=Manual \
                PRODUCT_BUNDLE_IDENTIFIER="$NEW_BUNDLE_IDENTIFIER"

      - name: Export IPA from archive
        script: |
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          NEW_BUNDLE_IDENTIFIER="com.mycompany.$CLIENT_ID"
          echo "Exporting for $NEW_BUNDLE_IDENTIFIER with $CLIENT_ID"
          xcodebuild -exportArchive \
                     -archivePath $FCI_BUILD_DIR/build/Runner.xcarchive \
                     -exportPath $FCI_BUILD_DIR/build \
                     -exportOptionsPlist ./clients/$CLIENT_ID/exportOptions.plist
      
      # - name: Build iOS for Release
      #   script: | 
      #     flutter build ios --release --build-number=$(date +%Y%m%d%H%M%S) --codesign

    artifacts:
      - build/ios/build/*.ipa  # Adjust based on your actual output directory from the export command
      - build/ios/Build/Products/Release-iphoneos/*.app
      - build/ios/Build/Products/Release-iphoneos/*.ipa
      - build/ios/ipa/*.ipa
      # - build/**/outputs/**/*.apk
      # - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      email:
        recipients:
          - alexalejandroem@gmail.com
