workflows:
  crete-themed-app-workflow:
    name: Create Themed app
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "Test app - Codemagic"

    triggering:
      events:
        - tag

    environment:
      flutter: stable    

    scripts:
      - name: Apply client configuration
        script: |
          # Assuming CM_TAG is set to the tag that triggered the build
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          echo "A Build is going to be performed for: $CLIENT_ID"
          echo "Copy assets for client"
          cp "clients/$CLIENT_ID/flutter_flow_theme.dart" "lib/flutter_flow/flutter_flow_theme.dart"
          cp "clients/$CLIENT_ID/app_launcher_icon.png" "assets/images/app_launcher_icon.png"
          cp "clients/$CLIENT_ID/app_splash_image.png" "assets/images/app_splash_image.png"
          echo "Add dependencies for preparing assets"
          flutter pub add flutter_launcher_icons
          flutter pub add flutter_native_splash
          flutter pub get
          echo "Applying configs"
          flutter pub run flutter_launcher_icons -f "clients/clients_flutter_launcher_icons.yaml"
          flutter pub run flutter_native_splash:create --path="clients/clients_flutter_native_splash.yaml"      
          echo "Successfully applied client configuration"
      
      - name: Change iOS Bundle Identifier
        script: |
          NEW_BUNDLE_IDENTIFIER="com.mycompany.$CLIENT_ID"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $NEW_BUNDLE_IDENTIFIER" "$FCI_BUILD_DIR/ios/Runner/Info.plist"
          echo "Bundle Identifier changed to $NEW_BUNDLE_IDENTIFIER"
          
      - name: Get Flutter packages
        script: | 
          flutter packages pub get

      #- name: Build AAB with Flutter
      #  script: | 
      #    flutter build appbundle --release

      - name: Build APK for Debug
        script: | 
          flutter build apk --debug
      
      - name: Build iOS for Release
        script: | 
          flutter build ios --release --build-number=$(date +%Y%m%d%H%M%S)  # Build number to avoid conflicts in versioning

    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      email:
        recipients:
          - alexalejandroem@gmail.com
