definitions:
  env_versions: &env_versions
    xcode: 14.2
    cocoapods: default

workflows:
  crete-themed-app-workflow:
    triggering:
      events:
        - tag
    name: Create Themed app
    instance_type: mac_mini_m1    
    environment:
      flutter: stable
      #ios_signing:
      #  provisioning_profiles:
      #    - profile: clientApp1
      #  certificates:
      #    - certificate: distributionCertificate

    scripts:
      - name: Extract CLIENT_ID
        script: |
          # Assuming FCI_BUILD_TAG is set to the tag that triggered the build
          CLIENT_ID=$(echo $FCI_BUILD_TAG | cut -d'_' -f1)
          echo "Extracted CLIENT_ID: $CLIENT_ID"
          # Export the CLIENT_ID so it can be used in subsequent scripts
          export CLIENT_ID

      - name: Copy Theme for CLIENT_ID to fproject 
        script: |
          cp "clients/$CLIENT_ID/flutter_flow_theme.dart" "lib/flutter_flow/flutter_flow_theme.dart"

      - name: Apply custom launcher icon
        script: |
          cp "clients/$CLIENT_ID/app_launcher_icon.png" "assets/images/app_launcher_icon.png"
          dart pub add flutter_launcher_icons
          flutter pub get
          flutter pub run flutter_launcher_icons -f "clients/clients_flutter_launcher_icons.yaml"

      - name: Apply custom splash icon
        script: |
          cp "clients/$CLIENT_ID/app_splash_image.png" "assets/images/app_splash_image.png"
          flutter pub add flutter_native_splash
          flutter pub get
          dart run flutter_native_splash:create --path="clients/clients_flutter_native_splash.yaml"      
          
      - name: Get Flutter packages
        script: | 
          flutter packages pub get

      - name: Build AAB with Flutter
        script: | 
          flutter build appbundle --release

      - name: Build APK for Debug
        script: | 
          flutter build apk --debug

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      #app_store_connect:
      #  api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #  key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #  issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - alexalejandroem@gmail.com
