workflows:
  crete-themed-app-workflow:
    name: Create Themed app
    instance_type: mac_mini_m1

    triggering:
      events:
        - tag

    environment:
      flutter: stable    

    scripts:
      - name: Apply client configuration
        script: |
          # Assuming CM_TAG is set to the tag that triggered the build
          CLIENT_ID=$(echo $CM_TAG | cut -d'_' -f1)
          echo "A Build is going to be performed for: $CLIENT_ID"
          echo "Copy assets for client"
          cp "clients/$CLIENT_ID/flutter_flow_theme.dart" "lib/flutter_flow/flutter_flow_theme.dart"
          cp "clients/$CLIENT_ID/app_launcher_icon.png" "assets/images/app_launcher_icon.png"
          cp "clients/$CLIENT_ID/app_splash_image.png" "assets/images/app_splash_image.png"
          echo "Add dependencies for preparing assets"
          flutter pub add flutter_launcher_icons
          flutter pub add flutter_native_splash
          flutter pub get
          echo "Applying configs"
          flutter pub run flutter_launcher_icons -f "clients/clients_flutter_launcher_icons.yaml"
          flutter pub run flutter_native_splash:create --path="clients/clients_flutter_native_splash.yaml"      
          echo "Successfully applied client configuration"
          
      - name: Get Flutter packages
        script: | 
          flutter packages pub get

      #- name: Build AAB with Flutter
      #  script: | 
      #    flutter build appbundle --release

      - name: Build APK for Debug
        script: | 
          flutter build apk --debug

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      #app_store_connect:
      #  api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #  key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #  issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - alexalejandroem@gmail.com
